import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: '1000px',
    margin: '20px auto',
    padding: '20px',
    background: 'white',
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: '1px solid #eee',
  },
  title: {
    fontSize: '24px',
    fontWeight: 600,
    color: '#333',
    marginBottom: '8px',
  },
  subtitle: {
    fontSize: '14px',
    color: '#666',
  },
  controlPanel: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    background: '#f9f9f9',
    borderRadius: '8px',
    marginBottom: '20px',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#444',
  },
  input: {
    width: '60px',
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid #ddd',
    borderRadius: '6px',
  },
  button: {
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: 500,
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  startButton: {
    background: '#10B981',
    color: 'white',
    flex: 1,
  },
  stopButton: {
    background: '#EF4444',
    color: 'white',
  },
  logsContainer: {
    background: '#1a1a2e',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '20px',
    maxHeight: '400px',
    overflowY: 'auto',
    fontFamily: 'Monaco, Consolas, monospace',
    fontSize: '13px',
  },
  logEntry: {
    padding: '4px 0',
    borderBottom: '1px solid #2a2a4e',
  },
  logTimestamp: {
    color: '#666',
    marginRight: '8px',
  },
  logInfo: { color: '#8b8b8b' },
  logSuccess: { color: '#10B981' },
  logWarning: { color: '#F59E0B' },
  logError: { color: '#EF4444' },
  logStep: { color: '#60A5FA', fontWeight: 600 },
  progressBar: {
    height: '8px',
    background: '#e5e7eb',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '20px',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #10B981, #3B82F6)',
    transition: 'width 0.3s ease',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '16px',
    marginBottom: '20px',
  },
  statCard: {
    padding: '16px',
    background: '#f9f9f9',
    borderRadius: '8px',
    textAlign: 'center',
  },
  statValue: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#333',
  },
  statLabel: {
    fontSize: '12px',
    color: '#666',
    marginTop: '4px',
  },
  section: {
    marginBottom: '24px',
    padding: '16px',
    background: '#f9f9f9',
    borderRadius: '8px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    marginBottom: '12px',
    color: '#444',
  },
  comparison: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  comparisonBox: {
    padding: '16px',
    background: 'white',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
  },
  promptBox: {
    padding: '12px',
    background: '#f3f4f6',
    borderRadius: '6px',
    fontSize: '13px',
    lineHeight: '1.5',
    maxHeight: '200px',
    overflow: 'auto',
    whiteSpace: 'pre-wrap',
  },
  testCase: {
    padding: '12px',
    marginBottom: '8px',
    background: 'white',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
  },
};
